version: '3.8'

services:
  api:
    image: node:18-alpine
    container_name: cinema-api
    restart: always
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cinema?schema=public"
    ports:
      - "3333:3333"
    volumes:
      - ./cinema-ts-api:/app
      - ./prisma:/app/prisma
    command: /app/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: cinema-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
